## LAB ACTIVITY 19
## NAME : SONALI R; REG NO : 22MID0061; COURSE CODE: CSI3007; LAB : L7+L8;
## DATE : 28/10/2025

## Data Analysis Using Pandas

In [4]:
## TASK-1

import pandas as pd   # Importing the pandas library for data handling

# Let's assume these are the number of runs scored by a player in 5 consecutive matches
runs = [45, 78, 0, 102, 56]  

# Creating a pandas Series from the list of runs
series_from_list = pd.Series(runs)

# Displaying the Series, which represents runs in each match
print(series_from_list)

0     45
1     78
2      0
3    102
4     56
dtype: int64

In [6]:
## TASK-2

import pandas as pd   # Importing pandas library to work with tabular data

# Creating a DataFrame with cricket player information
data = {
    'Player': ['Dhoni', 'Rohit Sharma', 'Jasprit Bumrah', 'Ravindra Jadeja'],  # Names of players
    'Age': [35, 38, 31, 36],        # Players' ages
    'Runs': [82, 64, 12, 45]        # Runs scored in a recent match (example data)
}

# Creating the DataFrame from the dictionary 'data'
df = pd.DataFrame(data)

# Printing the DataFrame to display player statistics
print(df)

            Player  Age  Runs
0            Dhoni   35    82
1     Rohit Sharma   38    64
2   Jasprit Bumrah   31    12
3  Ravindra Jadeja   36    45

In [12]:
## TASK-3

import pandas as pd   # Importing pandas for data manipulation

# Creating the first Series: runs scored by players in Match 1
match1_runs = pd.Series(
    [55, 70, 40],                # Runs scored
    index=["Rohit", "Dhoni", "Rahul"]  # Player names as index
)

# Creating the second Series: runs scored by players in Match 2
match2_runs = pd.Series(
    [60, 35, 45],                # Runs scored
    index=["Dhoni", "Rahul", "Hardik"]  # Notice the overlap: 'Dhoni' and 'Rahul' appear in both
)

# Performing element-wise multiplication
# Pandas aligns data based on the index (player names)
# Only players present in both Series ('Dhoni' and 'Rahul') will be multiplied
print(match1_runs * match2_runs)

Dhoni     4200.0
Hardik       NaN
Rahul     1400.0
Rohit        NaN
dtype: float64

In [14]:
## TASK-4

import pandas as pd   # Importing pandas library for Series operations

# Creating the first Series: runs scored by a batsman in the 1st innings
innings1_runs = pd.Series([45, 60, 75])   # Example: runs in three different matches

# Creating the second Series: runs scored by the same batsman in the 2nd innings
innings2_runs = pd.Series([30, 55, 80])   # Runs in the same three matches' 2nd innings

# Adding the two Series together to get total runs (1st + 2nd innings)
# This operation adds element-wise values since the indexes (0, 1, 2) align perfectly
total_runs = innings1_runs + innings2_runs

# Displaying the total runs scored across both innings for each match
print(total_runs)

0     75
1    115
2    155
dtype: int64

In [18]:
## TASK-5

import pandas as pd   # Import pandas

# Creating a MultiIndex Series: Team & Player as two levels
arrays = [
    ['India', 'India', 'Australia', 'Australia'],   # Team names
    ['Dhoni', 'Rohit', 'Smith', 'Warner']          # Player names
]

# Defining MultiIndex using the arrays
index = pd.MultiIndex.from_arrays(arrays, names=('Team', 'Player'))

# Creating Series: runs scored by each player
multi_s = pd.Series([82, 64, 95, 78], index=index)

# Display the MultiIndex Series
print(multi_s)

Team       Player
India      Dhoni     82
           Rohit     64
Australia  Smith     95
           Warner    78
dtype: int64

In [22]:
## TASK-6

import pandas as pd   # Import pandas

# Creating a MultiIndex Series: Team and Player
arrays = [
    ['India', 'India', 'Australia', 'Australia'],   # Teams
    ['Dhoni', 'Rohit', 'Smith', 'Warner']          # Players
]

# Define MultiIndex using the arrays
index = pd.MultiIndex.from_arrays(arrays, names=('Team', 'Player'))

# Create Series showing runs scored by each player
multi_s = pd.Series([82, 64, 95, 78], index=index)

# Display the MultiIndex Series
print(multi_s)

Team       Player
India      Dhoni     82
           Rohit     64
Australia  Smith     95
           Warner    78
dtype: int64

In [26]:
## TASK-7

import pandas as pd   # Import pandas

# Creating a MultiIndex Series: (Team, Player)
tuples = [
    ('India', 'Dhoni'),
    ('India', 'Rohit'),
    ('Australia', 'Smith'),
    ('Australia', 'Warner')
]

# Define MultiIndex from tuples with level names
index = pd.MultiIndex.from_tuples(tuples, names=('Team', 'Player'))

# Create Series showing runs scored by each player
multi_s = pd.Series([82, 64, 95, 78], index=index)

# Display the MultiIndex Series
print(multi_s)

Team       Player
India      Dhoni     82
           Rohit     64
Australia  Smith     95
           Warner    78
dtype: int64

In [30]:
## TASK-8

import pandas as pd   # Import pandas

# Create MultiIndex from product of two lists: Team × Player
index = pd.MultiIndex.from_product(
    [['India', 'Australia'], ['Dhoni', 'Rohit']],   # Teams × Players
    names=('Team', 'Player')
)

# Create Series: runs scored by each player
multi_s = pd.Series([82, 64, 95, 78], index=index)

# Display the MultiIndex Series
print(multi_s)

Team       Player
India      Dhoni     82
           Rohit     64
Australia  Dhoni     95
           Rohit     78
dtype: int64

In [32]:
## TASK-9

import pandas as pd   # Import pandas

# Create a DataFrame containing team and player information
df = pd.DataFrame({
    'Team': ['India', 'India', 'Australia', 'Australia'],   # Teams
    'Player': ['Dhoni', 'Rohit', 'Smith', 'Warner']         # Players
})

# Create MultiIndex from the DataFrame
index = pd.MultiIndex.from_frame(df, names=('Team', 'Player'))

# Create Series representing runs scored by each player
multi_s = pd.Series([82, 64, 95, 78], index=index)

# Display the MultiIndex Series
print(multi_s)

Team       Player
India      Dhoni     82
           Rohit     64
Australia  Smith     95
           Warner    78
dtype: int64

In [36]:
## TASK-10

import pandas as pd
import numpy as np

# -----------------------------------------------------------
# 1. Creating a MultiIndex Series in Different Ways
# -----------------------------------------------------------

arrays = [
    ["India", "India", "Australia", "Australia"],
    ["Virat", "Rohit", "Smith", "Warner"]
]
index = pd.MultiIndex.from_arrays(arrays, names=("Team", "Player"))
multi_s = pd.Series([82, 64, 95, 78], index=index)
print("MultiIndex Series from arrays:\n", multi_s, "\n")

tuples = [
    ("India", "Virat"), ("India", "Rohit"),
    ("Australia", "Smith"), ("Australia", "Warner")
]
index2 = pd.MultiIndex.from_tuples(tuples, names=("Team", "Player"))
multi_s2 = pd.Series([75, 68, 88, 90], index=index2)
print("MultiIndex Series from tuples:\n", multi_s2, "\n")

iterables = [["India", "Australia"], ["Virat", "Rohit"]]
index3 = pd.MultiIndex.from_product(iterables, names=("Team", "Player"))
multi_s3 = pd.Series(np.random.randint(40, 120, size=4), index=index3)
print("MultiIndex Series from product:\n", multi_s3, "\n")

# -----------------------------------------------------------
# 2. Accessing and Indexing
# -----------------------------------------------------------

print("Access all players from Team 'India':\n", multi_s.loc["India"], "\n")
print("Access specific element (Australia, Warner):\n", multi_s.loc[("Australia", "Warner")], "\n")

# -----------------------------------------------------------
# 3. Slicing in MultiIndex
# -----------------------------------------------------------

multi_s = multi_s.sort_index()  # prevent UnsortedIndexError
print("Slicing from India to Australia:\n", multi_s.loc["India":"Australia"], "\n")
print("Partial slice for all 'Virat':\n", multi_s.loc[:, "Virat"], "\n")

# -----------------------------------------------------------
# 4. Swapping and Reordering Levels
# -----------------------------------------------------------

print("Swapping levels:\n", multi_s.swaplevel(), "\n")
print("Reordering levels:\n", multi_s3.reorder_levels(["Player", "Team"]), "\n")

# -----------------------------------------------------------
# 5. Passing List of Arrays directly to Series / DataFrame
# -----------------------------------------------------------

multi_s_auto = pd.Series(
    np.random.randint(50, 120, size=4),
    index=pd.MultiIndex.from_arrays([["India", "India", "Australia", "Australia"],
                                     ["Virat", "Rohit", "Smith", "Warner"]])
)
print("MultiIndex Series constructed automatically:\n", multi_s_auto, "\n")

df_auto = pd.DataFrame(
    np.random.randint(40, 120, size=(4, 2)),
    index=pd.MultiIndex.from_arrays([["Match1", "Match1", "Match2", "Match2"],
                                     ["India", "Australia", "India", "Australia"]]),
    columns=["Runs", "StrikeRate"]
)
print("DataFrame with MultiIndex automatically:\n", df_auto, "\n")

# -----------------------------------------------------------
# 6. Data Alignment and Reindexing
# -----------------------------------------------------------

df = pd.DataFrame({
    "Virat": [85, 90, 95, 80],
    "Rohit": [82, 88, 92, 84]
}, index=pd.MultiIndex.from_arrays([["India", "India", "Australia", "Australia"],
                                    ["Innings1", "Innings2", "Innings1", "Innings2"]]))
print("Original DataFrame:\n", df, "\n")

mean_by_team = df.groupby(level=0).mean()
print("Mean by team:\n", mean_by_team, "\n")

aligned = mean_by_team.reindex(df.index, level=0)
print("Reindexed to align with original index:\n", aligned, "\n")

# -----------------------------------------------------------
# 7. Using xs() for Cross-Section
# -----------------------------------------------------------

print("Cross-section for 'Innings2':\n", df.xs("Innings2", level=1), "\n")

# -----------------------------------------------------------
# 8. Sorting and Removing Unused Levels
# -----------------------------------------------------------

unsorted = multi_s_auto.sample(frac=1)   # Shuffle randomly
print("Unsorted MultiIndex Series:\n", unsorted, "\n")
print("Sorted by index:\n", unsorted.sort_index(), "\n")

sub_df = df_auto[["Runs"]]   # Select one column
print("Unused levels before removing:\n", sub_df.columns, "\n")

if isinstance(sub_df.columns, pd.MultiIndex):
    sub_df.columns = sub_df.columns.remove_unused_levels()
    print("After remove_unused_levels:\n", sub_df.columns.levels, "\n")
else:
    print("Columns are not MultiIndex — no unused levels to remove.\n")

MultiIndex Series from arrays:
 Team       Player
India      Virat     82
           Rohit     64
Australia  Smith     95
           Warner    78
dtype: int64

MultiIndex Series from tuples:
 Team       Player
India      Virat     75
           Rohit     68
Australia  Smith     88
           Warner    90
dtype: int64

MultiIndex Series from product:
 Team       Player
India      Virat     73
           Rohit     83
Australia  Virat     82
           Rohit     78
dtype: int32

Access all players from Team 'India':
 Player
Virat    82
Rohit    64
dtype: int64

Access specific element (Australia, Warner):
 78

Slicing from India to Australia:
 Series([], dtype: int64)

Partial slice for all 'Virat':
 Team
India    82
dtype: int64

Swapping levels:
 Player  Team
Smith   Australia    95
Warner  Australia    78
Rohit   India        64
Virat   India        82
dtype: int64

Reordering levels:
 Player  Team
Virat   India        73
Rohit   India        83
Virat   Australia    82
Rohit   Australia    78
dtype: int32

MultiIndex Series constructed automatically:
 India      Virat      72
           Rohit      71
Australia  Smith     102
           Warner     80
dtype: int32

DataFrame with MultiIndex automatically:
                   Runs  StrikeRate
Match1 India        51         114
       Australia    65         117
Match2 India       109          70
       Australia    72          54

Original DataFrame:
                     Virat  Rohit
India     Innings1     85     82
          Innings2     90     88
Australia Innings1     95     92
          Innings2     80     84

Mean by team:
            Virat  Rohit
Australia   87.5   88.0
India       87.5   85.0

Reindexed to align with original index:
                     Virat  Rohit
India     Innings1   87.5   85.0
          Innings2   87.5   85.0
Australia Innings1   87.5   88.0
          Innings2   87.5   88.0

Cross-section for 'Innings2':
            Virat  Rohit
India         90     88
Australia     80     84

Unsorted MultiIndex Series:
 Australia  Warner     80
India      Rohit      71
Australia  Smith     102
India      Virat      72
dtype: int32

Sorted by index:
 Australia  Smith     102
           Warner     80
India      Rohit      71
           Virat      72
dtype: int32

Unused levels before removing:
 Index(['Runs'], dtype='object')

Columns are not MultiIndex — no unused levels to remove.

In [38]:
## TASK-11

# Program 1: Creating MultiIndex Series in different ways (Cricket Theme)
import pandas as pd
import numpy as np

# -----------------------------------------------------------
# From arrays → Creating a MultiIndex Series using arrays
# -----------------------------------------------------------
arrays = [["India", "India", "Australia", "Australia"],   # Teams
          ["Virat", "Rohit", "Smith", "Warner"]]          # Players
index = pd.MultiIndex.from_arrays(arrays, names=("Team", "Player"))
multi_s = pd.Series([82, 76, 91, 84], index=index)        # Players' scores
print("MultiIndex Series from arrays:\n", multi_s, "\n")

# -----------------------------------------------------------
# From tuples → Creating MultiIndex using list of tuples
# -----------------------------------------------------------
tuples = [("India", "Virat"), ("India", "Rohit"),
          ("Australia", "Smith"), ("Australia", "Warner")]
index2 = pd.MultiIndex.from_tuples(tuples, names=("Team", "Player"))
multi_s2 = pd.Series([85, 79, 90, 88], index=index2)      # Alternate scores
print("MultiIndex Series from tuples:\n", multi_s2, "\n")

# -----------------------------------------------------------
# From product → Using Cartesian product of iterables
# -----------------------------------------------------------
iterables = [["India", "Australia"], ["Virat", "Rohit"]]   # All combinations
index3 = pd.MultiIndex.from_product(iterables, names=("Team", "Player"))
multi_s3 = pd.Series(np.random.randint(50, 120, size=4), index=index3)  # Random scores
print("MultiIndex Series from product:\n", multi_s3, "\n")

MultiIndex Series from arrays:
 Team       Player
India      Virat     82
           Rohit     76
Australia  Smith     91
           Warner    84
dtype: int64

MultiIndex Series from tuples:
 Team       Player
India      Virat     85
           Rohit     79
Australia  Smith     90
           Warner    88
dtype: int64

MultiIndex Series from product:
 Team       Player
India      Virat      85
           Rohit     105
Australia  Virat      68
           Rohit      53
dtype: int32

In [40]:
## TASK-12

import pandas as pd
import numpy as np

# ------------------------------------------
# Example 1: MultiIndex from arrays (Teams & Players)
# ------------------------------------------
arrays = [
    ["TeamA", "TeamA", "TeamB", "TeamB"],  # Teams
    ["Player1", "Player2", "Player1", "Player2"]  # Players
]
index = pd.MultiIndex.from_arrays(arrays, names=("Team", "Player"))

# Random scores for matches
df1 = pd.DataFrame(
    np.random.randint(0, 101, size=(4, 2)),  # Scores out of 100
    index=index,
    columns=["Match1_Score", "Match2_Score"]
)
print("Example 1: MultiIndex from arrays\n", df1, "\n")

# ------------------------------------------
# Example 2: MultiIndex from tuples (Teams & Players)
# ------------------------------------------
tuples = [
    ("TeamA", "Player1"),
    ("TeamA", "Player2"),
    ("TeamB", "Player1"),
    ("TeamB", "Player2")
]
index2 = pd.MultiIndex.from_tuples(tuples, names=("Team", "Player"))

# Random batting averages
df2 = pd.DataFrame(
    np.random.uniform(20, 60, size=(4, 2)),  # Batting averages
    index=index2,
    columns=["Avg_Runs", "Strike_Rate"]
)
print("Example 2: MultiIndex from tuples\n", df2, "\n")

# ------------------------------------------
# Example 3: MultiIndex from product (Teams & Match types)
# ------------------------------------------
index3 = pd.MultiIndex.from_product(
    [["TeamA", "TeamB"], ["ODI", "T20"]],  # Teams and match formats
    names=("Team", "Format")
)

# Random scores for match formats
df3 = pd.DataFrame(
    np.random.randint(50, 300, size=(4, 2)),  # Runs scored
    index=index3,
    columns=["Runs1", "Runs2"]
)
print("Example 3: MultiIndex from product\n", df3, "\n")

# ------------------------------------------
# Example 4: MultiIndex from DataFrame columns (Teams & Players)
# ------------------------------------------
data = {
    "Team": ["TeamA", "TeamA", "TeamB", "TeamB"],
    "Player": ["Player1", "Player2", "Player1", "Player2"],
    "Runs": [45, 78, 60, 32]  # Runs scored in a match
}

df4 = pd.DataFrame(data)
df4 = df4.set_index(["Team", "Player"])  # Set Team & Player as index
print("Example 4: MultiIndex from DataFrame columns\n", df4, "\n")

Example 1: MultiIndex from arrays
                Match1_Score  Match2_Score
Team  Player
TeamA Player1            84            80
      Player2            34            44
TeamB Player1            56            51
      Player2            40            48

Example 2: MultiIndex from tuples
                 Avg_Runs  Strike_Rate
Team  Player
TeamA Player1  53.362105    47.713145
      Player2  42.207528    23.295920
TeamB Player1  21.814614    28.129358
      Player2  37.339849    56.026514

Example 3: MultiIndex from product
               Runs1  Runs2
Team  Format
TeamA ODI       291    278
      T20       113    114
TeamB ODI       182    270
      T20        72    156

Example 4: MultiIndex from DataFrame columns
                Runs
Team  Player
TeamA Player1    45
      Player2    78
TeamB Player1    60
      Player2    32

In [48]:
## TASK-13

# Program 2: Accessing and indexing in MultiIndex Series 
import pandas as pd

# Teams and Players as MultiIndex
arrays = [["TeamA", "TeamA", "TeamB", "TeamB"], ["Player1", "Player2", "Player1", "Player2"]]
index = pd.MultiIndex.from_arrays(arrays, names=("Team", "Player"))

# Series representing runs scored by each player
multi_s = pd.Series([45, 78, 60, 32], index=index)  # Runs scored

# Access all players' runs for TeamA
print("Access all players' runs for TeamA:\n", multi_s.loc["TeamA"], "\n")

# Access runs scored by TeamB's Player2
print("Access runs scored by TeamB's Player2:\n", multi_s.loc[("TeamB", "Player2")], "\n")

Access all players' runs for TeamA:
 Player
Player1    45
Player2    78
dtype: int64

Access runs scored by TeamB's Player2:
 32

In [46]:
## TASK-14

# Program 2: Accessing and indexing in MultiIndex Series 
import pandas as pd

# Teams and Players as MultiIndex
arrays = [["TeamA", "TeamA", "TeamB", "TeamB"], ["Player1", "Player2", "Player1", "Player2"]]
index = pd.MultiIndex.from_arrays(arrays, names=("Team", "Player"))

# Series representing runs scored by each player
multi_s = pd.Series([45, 78, 60, 32], index=index)  # Runs scored

# Access all players' runs for TeamA
print("Access all players' runs for TeamA:\n", multi_s.loc["TeamA"], "\n")

# Access runs scored by TeamB's Player2
print("Access runs scored by TeamB's Player2:\n", multi_s.loc[("TeamB", "Player2")], "\n")

Access all players' runs for TeamA:
 Player
Player1    45
Player2    78
dtype: int64

Access runs scored by TeamB's Player2:
 32

In [50]:
## TASK-15

# Program 3: Slicing in MultiIndex Series 
import pandas as pd

# Teams and Players as MultiIndex
arrays = [["TeamA", "TeamA", "TeamB", "TeamB"], ["Player1", "Player2", "Player1", "Player2"]]
index = pd.MultiIndex.from_arrays(arrays, names=("Team", "Player"))

# Series representing runs scored by each player
multi_s = pd.Series([45, 78, 60, 32], index=index)  # Runs scored

# Slice: get all players from TeamA to TeamB
print("Slicing from TeamA to TeamB:\n", multi_s.loc["TeamA":"TeamB"], "\n")

# Partial slice: get runs of all Player1 across teams
print("Partial slice for all Player1:\n", multi_s.loc[:, "Player1"], "\n")

Slicing from TeamA to TeamB:
 Team   Player
TeamA  Player1    45
       Player2    78
TeamB  Player1    60
       Player2    32
dtype: int64

Partial slice for all Player1:
 Team
TeamA    45
TeamB    60
dtype: int64

In [54]:
## TASK-16

# Program 4: Swapping and reordering levels in MultiIndex Series 
import pandas as pd

# Teams and Players as MultiIndex
arrays = [["TeamA", "TeamA", "TeamB", "TeamB"], ["Player1", "Player2", "Player1", "Player2"]]
index = pd.MultiIndex.from_arrays(arrays, names=("Team", "Player"))

# Series representing runs scored by each player
multi_s = pd.Series([45, 78, 60, 32], index=index)  # Runs scored

# Swap levels: Player becomes first level, Team becomes second
print("Swapping levels (Player first, Team second):\n", multi_s.swaplevel(), "\n")

# Reorder levels explicitly: Player first, then Team
print("Reordering levels explicitly:\n", multi_s.reorder_levels(["Player", "Team"]), "\n")

Swapping levels (Player first, Team second):
 Player   Team
Player1  TeamA    45
Player2  TeamA    78
Player1  TeamB    60
Player2  TeamB    32
dtype: int64

Reordering levels explicitly:
 Player   Team
Player1  TeamA    45
Player2  TeamA    78
Player1  TeamB    60
Player2  TeamB    32
dtype: int64

In [56]:
## TASK-17

# Program 5: Passing arrays directly to create MultiIndex in Series/DataFrame 
import pandas as pd
import numpy as np

# Series: runs scored by players with automatic MultiIndex (Team & Player)
multi_s_auto = pd.Series(
    np.random.randint(10, 101, 4),  # Random runs between 10 and 100
    index=pd.MultiIndex.from_arrays([["TeamA", "TeamA", "TeamB", "TeamB"], 
                                     ["Player1", "Player2", "Player1", "Player2"]]),
    name="Runs"
)
print("MultiIndex Series constructed automatically:\n", multi_s_auto, "\n")

# DataFrame: multiple match scores with automatic MultiIndex (Team & Match)
df_auto = pd.DataFrame(
    np.random.randint(50, 301, size=(4, 2)),  # Runs scored in matches
    index=pd.MultiIndex.from_arrays([["TeamA", "TeamA", "TeamB", "TeamB"],
                                     ["Match1", "Match2", "Match1", "Match2"]]),
    columns=["Score1", "Score2"]
)
print("DataFrame with MultiIndex automatically:\n", df_auto, "\n")

MultiIndex Series constructed automatically:
 TeamA  Player1    20
       Player2    73
TeamB  Player1    18
       Player2    70
Name: Runs, dtype: int32

DataFrame with MultiIndex automatically:
               Score1  Score2
TeamA Match1      73     206
      Match2     114     186
TeamB Match1     225      68
      Match2     208     141

In [58]:
## TASK-18

# Program 6: Data alignment and reindexing with MultiIndex 
import pandas as pd

# Original DataFrame: Runs scored by players in two matches
df = pd.DataFrame({
    "Match1": [45, 78, 60, 32],  # Runs in Match 1
    "Match2": [50, 82, 65, 40]   # Runs in Match 2
}, index=pd.MultiIndex.from_arrays([["TeamA", "TeamA", "TeamB", "TeamB"], 
                                   ["Player1", "Player2", "Player1", "Player2"]]))
print("Original DataFrame (Runs by Players):\n", df, "\n")

# Group by Team (first level) and compute mean runs
mean_by_team = df.groupby(level=0).mean()
print("Mean runs by Team:\n", mean_by_team, "\n")

# Reindexing to align mean runs with original player index
aligned = mean_by_team.reindex(df.index, level=0)
print("Reindexed mean runs aligned with original players:\n", aligned, "\n")

Original DataFrame (Runs by Players):
                Match1  Match2
TeamA Player1      45      50
      Player2      78      82
TeamB Player1      60      65
      Player2      32      40

Mean runs by Team:
        Match1  Match2
TeamA    61.5    66.0
TeamB    46.0    52.5

Reindexed mean runs aligned with original players:
                Match1  Match2
TeamA Player1    61.5    66.0
      Player2    61.5    66.0
TeamB Player1    46.0    52.5
      Player2    46.0    52.5

In [60]:
## TASK-19

# Program 8: Sorting MultiIndex and removing unused levels 
import pandas as pd
import numpy as np

# Unsorted MultiIndex Series: Runs scored by players
multi_s = pd.Series(
    np.random.randint(10, 101, 4),  # Runs between 10 and 100
    index=pd.MultiIndex.from_arrays([["TeamB", "TeamA", "TeamB", "TeamA"], 
                                     ["Player1", "Player2", "Player2", "Player1"]])
)
print("Unsorted MultiIndex Series (Runs):\n", multi_s, "\n")

# Sort Series by Team and Player
print("Sorted by Team and Player:\n", multi_s.sort_index(), "\n")

# DataFrame: Multiple match scores for teams
df = pd.DataFrame(
    np.random.randint(50, 301, size=(4, 2)),  # Runs scored
    index=pd.MultiIndex.from_arrays([["TeamA", "TeamA", "TeamB", "TeamB"], 
                                     ["Match1", "Match2", "Match1", "Match2"]]),
    columns=pd.MultiIndex.from_arrays([["Score1", "Score2"], ["ODI", "T20"]])  # Match types
)
print("Before removing unused levels:\n", df.columns.levels, "\n")

# Keep only Score1 column
sub_df = df[["Score1"]]  # Drop Score2
print("After removing unused levels:\n", sub_df.columns.remove_unused_levels().levels, "\n")

Unsorted MultiIndex Series (Runs):
 TeamB  Player1    92
TeamA  Player2    72
TeamB  Player2    57
TeamA  Player1    57
dtype: int32

Sorted by Team and Player:
 TeamA  Player1    57
       Player2    72
TeamB  Player1    92
       Player2    57
dtype: int32

Before removing unused levels:
 [['Score1', 'Score2'], ['ODI', 'T20']]

After removing unused levels:
 [['Score1'], ['ODI']]

## Creating DataFrames (different ways)

In [64]:
## TASK-20

# Program 1: Creating DataFrames in different ways 
import pandas as pd
import numpy as np

# ------------------------------------------
# 1. From dictionary of lists: Player info
# ------------------------------------------
data1 = {
    "Player": ["Virat", "Rohit", "Jadeja"],  # Player names
    "Age": [34, 31, 30],                     # Player ages
    "Runs": [75, 88, 60]                     # Runs scored in a match
}
df1 = pd.DataFrame(data1)
print("DataFrame from dictionary of lists (Player info):\n", df1, "\n")

# ------------------------------------------
# 2. From dictionary of Series: Player scores per match
# ------------------------------------------
data2 = {
    "ODI": pd.Series([85, 90, 78], index=["Virat", "Rohit", "Jadeja"]),   # ODI runs
    "T20": pd.Series([45, 60, 40], index=["Virat", "Rohit", "Jadeja"])    # T20 runs
}
df2 = pd.DataFrame(data2)
print("DataFrame from dictionary of Series (Match-wise scores):\n", df2, "\n")

# ------------------------------------------
# 3. From NumPy array: Random match stats
# ------------------------------------------
df3 = pd.DataFrame(
    np.random.randint(10, 101, size=(3, 3)),  # Random runs between 10-100
    columns=["Match1", "Match2", "Match3"]   # Match columns
)
print("DataFrame from NumPy array (Random match scores):\n", df3, "\n")

DataFrame from dictionary of lists (Player info):
    Player  Age  Runs
0   Virat   34    75
1   Rohit   31    88
2  Jadeja   30    60

DataFrame from dictionary of Series (Match-wise scores):
         ODI  T20
Virat    85   45
Rohit    90   60
Jadeja   78   40

DataFrame from NumPy array (Random match scores):
    Match1  Match2  Match3
0      37      98      75
1      16      32      33
2      23      99      73

In [68]:
## TASK-21

# Program 2: Accessing rows and columns in DataFrame 
import pandas as pd

# Cricket player stats
data = {
    "Player": ["Virat", "Rohit", "Jadeja", "Bumrah"],  # Player names
    "Age": [34, 31, 30, 29],                           # Player ages
    "Runs": [75, 88, 60, 45]                           # Runs scored in last match
}
df = pd.DataFrame(data)
print("Original DataFrame (Player stats):\n", df, "\n")

# Access single column: Runs scored
print("Accessing single column (Runs):\n", df["Runs"], "\n")

# Access multiple columns: Player names and ages
print("Accessing multiple columns (Player & Age):\n", df[["Player", "Age"]], "\n")

# Access row by index label: 3rd player
print("Access row using loc (3rd player):\n", df.loc[2], "\n")

# Access row by integer location: 2nd player
print("Access row using iloc (2nd player):\n", df.iloc[1], "\n")

Original DataFrame (Player stats):
    Player  Age  Runs
0   Virat   34    75
1   Rohit   31    88
2  Jadeja   30    60
3  Bumrah   29    45

Accessing single column (Runs):
 0    75
1    88
2    60
3    45
Name: Runs, dtype: int64

Accessing multiple columns (Player & Age):
    Player  Age
0   Virat   34
1   Rohit   31
2  Jadeja   30
3  Bumrah   29

Access row using loc (3rd player):
 Player    Jadeja
Age           30
Runs          60
Name: 2, dtype: object

Access row using iloc (2nd player):
 Player    Rohit
Age          31
Runs         88
Name: 1, dtype: object

In [70]:
## TASK-22

# Program 3: Indexing and Slicing in DataFrame 
import pandas as pd

# Cricket player stats
data = {
    "Player": ["Virat", "Rohit", "Jadeja", "Bumrah", "Dhawan"],  # Player names
    "Age": [34, 31, 30, 29, 33],                                 # Player ages
    "Runs": [75, 88, 60, 45, 90]                                  # Runs scored in last match
}
df = pd.DataFrame(data)
print("Original DataFrame (Player stats):\n", df, "\n")

# Slice first three rows (top 3 players)
print("First three rows:\n", df[:3], "\n")

# Slice rows 2 to 4 using loc
print("Rows 2 to 4:\n", df.loc[1:3], "\n")

# Slice specific columns: Player names and Runs
print("Columns Player and Runs:\n", df.loc[:, ["Player", "Runs"]], "\n")

# Conditional selection: players who scored more than 70 runs
print("Rows where Runs > 70:\n", df[df["Runs"] > 70], "\n")

Original DataFrame (Player stats):
    Player  Age  Runs
0   Virat   34    75
1   Rohit   31    88
2  Jadeja   30    60
3  Bumrah   29    45
4  Dhawan   33    90

First three rows:
    Player  Age  Runs
0   Virat   34    75
1   Rohit   31    88
2  Jadeja   30    60

Rows 2 to 4:
    Player  Age  Runs
1   Rohit   31    88
2  Jadeja   30    60
3  Bumrah   29    45

Columns Player and Runs:
    Player  Runs
0   Virat    75
1   Rohit    88
2  Jadeja    60
3  Bumrah    45
4  Dhawan    90

Rows where Runs > 70:
    Player  Age  Runs
0   Virat   34    75
1   Rohit   31    88
4  Dhawan   33    90

In [74]:
## TASK-23

# Program 4: Adding, Updating, and Deleting Data in DataFrame 
import pandas as pd

# Initial cricket player info
df = pd.DataFrame({
    "Player": ["Virat", "Rohit", "Jadeja"],  # Player names
    "Age": [34, 31, 30]                       # Player ages
})
print("Original DataFrame (Player info):\n", df, "\n")

# Adding new column: Runs scored in last match
df["Runs"] = [75, 88, 60]
print("After adding Runs column:\n", df, "\n")

# Updating values: Rohit's age
df.at[1, "Age"] = 32
print("After updating Age of Rohit:\n", df, "\n")

# Deleting column: remove Runs
df = df.drop("Runs", axis=1)
print("After deleting Runs column:\n", df, "\n")

# Deleting row: remove Jadeja
df = df.drop(2, axis=0)
print("After deleting row with index 2:\n", df, "\n")

Original DataFrame (Player info):
    Player  Age
0   Virat   34
1   Rohit   31
2  Jadeja   30

After adding Runs column:
    Player  Age  Runs
0   Virat   34    75
1   Rohit   31    88
2  Jadeja   30    60

After updating Age of Rohit:
    Player  Age  Runs
0   Virat   34    75
1   Rohit   32    88
2  Jadeja   30    60

After deleting Runs column:
    Player  Age
0   Virat   34
1   Rohit   32
2  Jadeja   30

After deleting row with index 2:
   Player  Age
0  Virat   34
1  Rohit   32

In [76]:
## TASK-24

# Program 5: Handling Missing Data in DataFrame 
import pandas as pd
import numpy as np

# Cricket player stats with some missing data
df = pd.DataFrame({
    "Player": ["Virat", "Rohit", "Jadeja"],  # Player names
    "Runs": [75, np.nan, 60],                # Runs scored (missing for Rohit)
    "Balls": [50, 45, np.nan]                # Balls faced (missing for Jadeja)
})
print("Original DataFrame with NaN values:\n", df, "\n")

# Detect missing values
print("Detect missing values:\n", df.isnull(), "\n")

# Fill missing values with 0
print("Fill missing values with 0:\n", df.fillna(0), "\n")

# Drop rows with missing values
print("Drop rows with missing values:\n", df.dropna(), "\n")

Original DataFrame with NaN values:
    Player  Runs  Balls
0   Virat  75.0   50.0
1   Rohit   NaN   45.0
2  Jadeja  60.0    NaN

Detect missing values:
    Player   Runs  Balls
0   False  False  False
1   False   True  False
2   False  False   True

Fill missing values with 0:
    Player  Runs  Balls
0   Virat  75.0   50.0
1   Rohit   0.0   45.0
2  Jadeja  60.0    0.0

Drop rows with missing values:
   Player  Runs  Balls
0  Virat  75.0   50.0

In [78]:
## TASK-25

# Program 6: Data Alignment and Reindexing in DataFrame 
import pandas as pd

# Runs scored by players in two different matches
df1 = pd.DataFrame({"Runs": [75, 88, 60]}, index=["Virat", "Rohit", "Jadeja"])
df2 = pd.DataFrame({"Runs": [92, 45]}, index=["Rohit", "Bumrah"])

print("DataFrame 1 (Match 1 runs):\n", df1, "\n")
print("DataFrame 2 (Match 2 runs):\n", df2, "\n")

# Automatic alignment in arithmetic: sum of runs where players match
print("Adding runs from both matches:\n", df1 + df2, "\n")

# Reindexing: include all players, fill missing runs with 0
df3 = df1.reindex(["Virat", "Rohit", "Jadeja", "Bumrah"], fill_value=0)
print("Reindexed DataFrame with all players:\n", df3, "\n")

DataFrame 1 (Match 1 runs):
         Runs
Virat     75
Rohit     88
Jadeja    60

DataFrame 2 (Match 2 runs):
         Runs
Rohit     92
Bumrah    45

Adding runs from both matches:
          Runs
Bumrah    NaN
Jadeja    NaN
Rohit   180.0
Virat     NaN

Reindexed DataFrame with all players:
         Runs
Virat     75
Rohit     88
Jadeja    60
Bumrah     0

In [82]:
## TASK-26

# Program 7: Sorting and Grouping in DataFrame 
import pandas as pd

# Cricket player stats
data = {
    "Player": ["Virat", "Rohit", "Jadeja", "Bumrah", "Dhawan"],  # Player names
    "Age": [34, 31, 30, 29, 33],                                 # Player ages
    "Runs": [75, 88, 60, 45, 90]                                  # Runs scored in last match
}
df = pd.DataFrame(data)
print("Original DataFrame (Player stats):\n", df, "\n")

# Sorting by Runs scored
print("Sorted by Runs:\n", df.sort_values(by="Runs"), "\n")

# Grouping by Age and computing average runs
grouped = df.groupby("Age")["Runs"].mean()
print("Average runs grouped by Age:\n", grouped, "\n")

Original DataFrame (Player stats):
    Player  Age  Runs
0   Virat   34    75
1   Rohit   31    88
2  Jadeja   30    60
3  Bumrah   29    45
4  Dhawan   33    90

Sorted by Runs:
    Player  Age  Runs
3  Bumrah   29    45
2  Jadeja   30    60
0   Virat   34    75
1   Rohit   31    88
4  Dhawan   33    90

Average runs grouped by Age:
 Age
29    45.0
30    60.0
31    88.0
33    90.0
34    75.0
Name: Runs, dtype: float64

In [84]:
## TASK-27

# Grouping Example: Series 
import pandas as pd

# Runs scored by players
runs = pd.Series([75, 88, 60, 45],
                 index=["Virat", "Rohit", "Jadeja", "Bumrah"])

# Player roles (Batsman/Bowler)
role = pd.Series(["Batsman", "Batsman", "Allrounder", "Bowler"],
                 index=["Virat", "Rohit", "Jadeja", "Bumrah"])

# Grouping by role (no aggregation yet)
grouped_series = runs.groupby(role)
print("Grouped Series by Player Role (just groups, no aggregation):\n", grouped_series, "\n")

# Accessing a specific group: Batsmen
print("Batsmen group:\n", grouped_series.get_group("Batsman"), "\n")

Grouped Series by Player Role (just groups, no aggregation):
 <pandas.core.groupby.generic.SeriesGroupBy object at 0x0000018529F6D880>

Batsmen group:
 Virat    75
Rohit    88
dtype: int64

In [86]:
## TASK-28

# Aggregation Example: Series 
# Aggregation on grouped Series to compute stats per player role

# Compute mean runs per role
aggregated_series = grouped_series.mean()
print("Aggregated Series (mean runs per player role):\n", aggregated_series, "\n")

# Other aggregations
print("Total runs per role:\n", grouped_series.sum(), "\n")
print("Maximum runs scored by a player in each role:\n", grouped_series.max(), "\n")

Aggregated Series (mean runs per player role):
 Allrounder    60.0
Batsman       81.5
Bowler        45.0
dtype: float64

Total runs per role:
 Allrounder     60
Batsman       163
Bowler         45
dtype: int64

Maximum runs scored by a player in each role:
 Allrounder    60
Batsman       88
Bowler        45
dtype: int64

In [88]:
## TASK-29

# Example: Grouping and Aggregating for Series / MultiLevel Series 
import pandas as pd

# Single Series: Runs scored by players
runs = pd.Series([75, 88, 60, 45],
                 index=["Virat", "Rohit", "Jadeja", "Bumrah"])
role = pd.Series(["Batsman", "Batsman", "Allrounder", "Bowler"],
                 index=["Virat", "Rohit", "Jadeja", "Bumrah"])

# Grouping runs by player role and calculating mean
grouped_series = runs.groupby(role).mean()
print("Mean runs by player role (Series):\n", grouped_series, "\n")

# MultiLevel Series: Team and Player
arrays = [
    ["TeamA", "TeamA", "TeamB", "TeamB"],
    ["Virat", "Rohit", "Jadeja", "Bumrah"]
]
index = pd.MultiIndex.from_arrays(arrays, names=("Team", "Player"))
multi_s = pd.Series([75, 88, 60, 45], index=index)

# Group by first level (Team) and compute mean runs
grouped_multi = multi_s.groupby(level=0).mean()
print("Mean runs by team (MultiLevel Series):\n", grouped_multi, "\n")

Mean runs by player role (Series):
 Allrounder    60.0
Batsman       81.5
Bowler        45.0
dtype: float64

Mean runs by team (MultiLevel Series):
 Team
TeamA    81.5
TeamB    52.5
dtype: float64

In [90]:
## TASK-30

# Grouping (DataFrame) Example 
import pandas as pd

# DataFrame: Player stats
df = pd.DataFrame({
    "Role": ["Batsman", "Batsman", "Allrounder", "Bowler"],  # Player roles
    "Player": ["Virat", "Rohit", "Jadeja", "Bumrah"],        # Player names
    "Runs": [75, 88, 60, 45]                                  # Runs scored
})

# Grouping by Role (no aggregation yet)
grouped_df = df.groupby("Role")
print("Grouped DataFrame by Player Role (just groups, no aggregation):\n", grouped_df, "\n")

# Accessing one group: Batsmen
print("Batsmen group in DataFrame:\n", grouped_df.get_group("Batsman"), "\n")

Grouped DataFrame by Player Role (just groups, no aggregation):
 <pandas.core.groupby.generic.DataFrameGroupBy object at 0x0000018528FDC440>

Batsmen group in DataFrame:
       Role Player  Runs
0  Batsman  Virat    75
1  Batsman  Rohit    88

In [92]:
## TASK-31

# Aggregating DataFrame Example 
# Aggregation on grouped DataFrame to compute stats per player role
import pandas as pd

# DataFrame: Player stats
df = pd.DataFrame({
    "Role": ["Batsman", "Batsman", "Allrounder", "Bowler"],  # Player roles
    "Player": ["Virat", "Rohit", "Jadeja", "Bumrah"],        # Player names
    "Runs": [75, 88, 60, 45]                                  # Runs scored
})

# Grouping by Role
grouped_df = df.groupby("Role")

# Compute mean runs per role
aggregated_df = grouped_df["Runs"].mean()
print("Aggregated DataFrame (mean runs per role):\n", aggregated_df, "\n")

# Multiple aggregations: mean, sum, max runs per role
multi_agg_df = grouped_df.agg({
    "Runs": ["mean", "sum", "max"]
})
print("Aggregated DataFrame (multiple stats per role):\n", multi_agg_df, "\n")

Aggregated DataFrame (mean runs per role):
 Role
Allrounder    60.0
Batsman       81.5
Bowler        45.0
Name: Runs, dtype: float64

Aggregated DataFrame (multiple stats per role):
             Runs
            mean  sum max
Role
Allrounder  60.0   60  60
Batsman     81.5  163  88
Bowler      45.0   45  45

In [94]:
## TASK-32

import pandas as pd

# ------------------------------------------
# Sample DataFrame: Cricket player stats
# ------------------------------------------
df = pd.DataFrame({
    "Team": ["TeamA", "TeamA", "TeamB", "TeamB", "TeamA", "TeamB"],  # Teams
    "Player": ["Virat", "Rohit", "Jadeja", "Bumrah", "Dhawan", "Hardik"],  # Players
    "Runs": [75, 88, 60, 45, 90, 70],        # Runs scored in recent matches
    "Balls": [50, 45, 40, 30, 55, 50]        # Balls faced
})

print("Original DataFrame (Player stats):\n", df, "\n")

# ------------------------------------------
# Grouping by Team (no aggregation yet)
# ------------------------------------------
grouped = df.groupby("Team")
print("Groups formed by Team:\n", grouped.groups, "\n")

# Access a specific group: TeamA
print("TeamA group:\n", grouped.get_group("TeamA"), "\n")

# ------------------------------------------
# Aggregating after grouping
# ------------------------------------------
# 1. Single aggregation function: mean runs per team
mean_runs = grouped["Runs"].mean()
print("Mean Runs per Team:\n", mean_runs, "\n")

# 2. Multiple aggregation functions: runs and balls stats
agg_stats = grouped.agg({
    "Runs": ["mean", "max", "min"],
    "Balls": ["sum", "mean"]
})
print("Aggregated stats per Team:\n", agg_stats, "\n")

# ------------------------------------------
# Optional: filtering groups (e.g., teams with mean runs > 70)
# ------------------------------------------
high_scoring_team = grouped.filter(lambda x: x["Runs"].mean() > 70)
print("Teams with mean runs > 70:\n", high_scoring_team, "\n")

Original DataFrame (Player stats):
     Team  Player  Runs  Balls
0  TeamA   Virat    75     50
1  TeamA   Rohit    88     45
2  TeamB  Jadeja    60     40
3  TeamB  Bumrah    45     30
4  TeamA  Dhawan    90     55
5  TeamB  Hardik    70     50

Groups formed by Team:
 {'TeamA': [0, 1, 4], 'TeamB': [2, 3, 5]}

TeamA group:
     Team  Player  Runs  Balls
0  TeamA   Virat    75     50
1  TeamA   Rohit    88     45
4  TeamA  Dhawan    90     55

Mean Runs per Team:
 Team
TeamA    84.333333
TeamB    58.333333
Name: Runs, dtype: float64

Aggregated stats per Team:
             Runs         Balls
            mean max min   sum  mean
Team
TeamA  84.333333  90  75   150  50.0
TeamB  58.333333  70  45   120  40.0

Teams with mean runs > 70:
     Team  Player  Runs  Balls
0  TeamA   Virat    75     50
1  TeamA   Rohit    88     45
4  TeamA  Dhawan    90     55

#### Difference between grouping/ aggregating in series and dataframes
- In grouping, a Series can be grouped only by another Series or index level, while a DataFrame can be grouped by one or more columns.

#### Series aggregation operates on a single column and returns a Series, whereas DataFrame aggregation can operate on multiple columns and return a DataFrame.

- Series is simpler and suitable for single-column data, while DataFrame is more powerful for handling complex, multi-column datasets.

In [99]:
## TASK-33

# Series Grouping Example 
import pandas as pd

# Runs scored by players
runs = pd.Series([75, 88, 60, 45], index=["Virat", "Rohit", "Jadeja", "Bumrah"])

# Player roles (Batsman / Allrounder / Bowler)
role = pd.Series(["Batsman", "Batsman", "Allrounder", "Bowler"], 
                 index=["Virat", "Rohit", "Jadeja", "Bumrah"])

# Grouping runs by player role
grouped_series = runs.groupby(role)

# Display groups
print("Grouped Series by Player Role:\n", grouped_series, "\n")

# Access a specific group: Batsmen
print("Batsmen group:\n", grouped_series.get_group("Batsman"), "\n")

Grouped Series by Player Role:
 <pandas.core.groupby.generic.SeriesGroupBy object at 0x00000185291FA690>

Batsmen group:
 Virat    75
Rohit    88
dtype: int64

In [101]:
## TASK-34

# DataFrame Grouping Example 
import pandas as pd

# DataFrame: Player stats
df = pd.DataFrame({
    "Role": ["Batsman", "Batsman", "Allrounder", "Bowler"],  # Player roles
    "Player": ["Virat", "Rohit", "Jadeja", "Bumrah"],        # Player names
    "Runs": [75, 88, 60, 45]                                  # Runs scored
})

# Grouping by Role
grouped_df = df.groupby("Role")

# Display groups (keys)
print("Groups formed by Role:\n", grouped_df.groups, "\n")

# Access a specific group: Batsmen
print("Batsmen group:\n", grouped_df.get_group("Batsman"), "\n")

Groups formed by Role:
 {'Allrounder': [2], 'Batsman': [0, 1], 'Bowler': [3]}

Batsmen group:
       Role Player  Runs
0  Batsman  Virat    75
1  Batsman  Rohit    88

In [103]:
## TASK-35

import pandas as pd

# ------------------------------------------
# 1. Series Example: Runs scored by players
# ------------------------------------------
runs_series = pd.Series([75, 88, 60, 45],
                        index=["Virat", "Rohit", "Jadeja", "Bumrah"])
role_series = pd.Series(["Batsman", "Batsman", "Allrounder", "Bowler"],
                        index=["Virat", "Rohit", "Jadeja", "Bumrah"])

# Grouping (creates groups by role, no aggregation yet)
grouped_series = runs_series.groupby(role_series)
print("Grouped Series by Player Role (no aggregation):")
for role, group in grouped_series:
    print(f"{role}: {group.values}")
print()

# Aggregating (mean runs per role)
aggregated_series = grouped_series.mean()
print("Aggregated Series (mean runs per role):")
print(aggregated_series)
print("\n" + "="*50 + "\n")

# ------------------------------------------
# 2. DataFrame Example: Player stats
# ------------------------------------------
df = pd.DataFrame({
    "Role": ["Batsman", "Batsman", "Allrounder", "Bowler"],
    "Player": ["Virat", "Rohit", "Jadeja", "Bumrah"],
    "Runs": [75, 88, 60, 45],
    "Balls": [50, 45, 40, 30]  # Balls faced
})

# Grouping by Role (creates groups)
grouped_df = df.groupby("Role")
print("Grouped DataFrame by Player Role (no aggregation):")
for role, group in grouped_df:
    print(f"{role} group:\n{group}\n")

# Aggregating (mean and sum for numeric columns)
aggregated_df = grouped_df.agg({
    "Runs": ["mean", "sum"],
    "Balls": ["mean", "sum"]
})
print("Aggregated DataFrame (Runs and Balls stats per Role):")
print(aggregated_df)

Grouped Series by Player Role (no aggregation):
Allrounder: [60]
Batsman: [75 88]
Bowler: [45]

Aggregated Series (mean runs per role):
Allrounder    60.0
Batsman       81.5
Bowler        45.0
dtype: float64

==================================================

Grouped DataFrame by Player Role (no aggregation):
Allrounder group:
         Role  Player  Runs  Balls
2  Allrounder  Jadeja    60     40

Batsman group:
      Role Player  Runs  Balls
0  Batsman  Virat    75     50
1  Batsman  Rohit    88     45

Bowler group:
     Role  Player  Runs  Balls
3  Bowler  Bumrah    45     30

Aggregated DataFrame (Runs and Balls stats per Role):
            Runs      Balls
            mean  sum  mean sum
Role
Allrounder  60.0   60  40.0  40
Batsman     81.5  163  47.5  95
Bowler      45.0   45  30.0  30

In [105]:
## TASK-36

# Merging DataFrames Example 
import pandas as pd

# DataFrame 1: Player teams
df1 = pd.DataFrame({
    "Player": ["Virat", "Rohit", "Jadeja", "Bumrah"],
    "Team": ["TeamA", "TeamB", "TeamA", "TeamB"]
})

# DataFrame 2: Player runs in recent match
df2 = pd.DataFrame({
    "Player": ["Virat", "Rohit", "Jadeja", "Dhawan"],
    "Runs": [75, 88, 60, 90]
})

# Inner merge: only players present in both DataFrames
inner_merge = pd.merge(df1, df2, on="Player", how="inner")
print("Inner Merge (Players in both Team & Runs DataFrames):\n", inner_merge, "\n")

# Outer merge: all players from both DataFrames
outer_merge = pd.merge(df1, df2, on="Player", how="outer")
print("Outer Merge (All players from both DataFrames):\n", outer_merge, "\n")

Inner Merge (Players in both Team & Runs DataFrames):
    Player   Team  Runs
0   Virat  TeamA    75
1   Rohit  TeamB    88
2  Jadeja  TeamA    60

Outer Merge (All players from both DataFrames):
    Player   Team  Runs
0  Bumrah  TeamB   NaN
1  Dhawan    NaN  90.0
2  Jadeja  TeamA  60.0
3   Rohit  TeamB  88.0
4   Virat  TeamA  75.0

In [107]:
## TASK-37

# Merging DataFrames on different keys 
import pandas as pd

# DataFrame 1: Player IDs and Names
df1 = pd.DataFrame({
    "PlayerID": [1, 2, 3],
    "Player": ["Virat", "Rohit", "Jadeja"]
})

# DataFrame 2: Player scores with a different key column name
df2 = pd.DataFrame({
    "PID": [2, 3, 4],
    "Runs": [88, 60, 90]
})

# Merge using different column names
merged_df = pd.merge(df1, df2, left_on="PlayerID", right_on="PID", how="inner")
print("Merge on different keys (Players present in both DataFrames):\n", merged_df)

Merge on different keys (Players present in both DataFrames):
    PlayerID  Player  PID  Runs
0         2   Rohit    2    88
1         3  Jadeja    3    60

In [109]:
## TASK-38

# Handling overlapping column names 
import pandas as pd

# DataFrame 1: Player runs in previous match
df1 = pd.DataFrame({
    "Player": ["Virat", "Rohit"],
    "Runs": [75, 88]
})

# DataFrame 2: Player runs in current match
df2 = pd.DataFrame({
    "Player": ["Rohit", "Jadeja"],
    "Runs": [90, 60]
})

# Merge with custom suffixes for overlapping column names
merged_df = pd.merge(df1, df2, on="Player", how="outer", suffixes=("_Prev", "_Curr"))
print("Merge with custom suffixes (Previous and Current Runs):\n", merged_df)

Merge with custom suffixes (Previous and Current Runs):
    Player  Runs_Prev  Runs_Curr
0  Jadeja        NaN       60.0
1   Rohit       88.0       90.0
2   Virat       75.0        NaN

In [111]:
## TASK-39

# Merging using indexes 
import pandas as pd

# DataFrame 1: Player runs
df1 = pd.DataFrame({"Runs": [75, 88]}, index=["Virat", "Rohit"])

# DataFrame 2: Player team
df2 = pd.DataFrame({"Team": ["TeamA", "TeamB"]}, index=["Virat", "Rohit"])

# Merge using row indexes
merged_index_df = pd.merge(df1, df2, left_index=True, right_index=True)
print("Merge using indexes (Player Runs with Team):\n", merged_index_df)

Merge using indexes (Player Runs with Team):
        Runs   Team
Virat    75  TeamA
Rohit    88  TeamB

#### Summary table
- df.pivot_table(values='NumericColumn', index='RowCategory', columns='ColumnCategory', aggfunc='mean')
values → numeric column to summarize

- index → row labels

- columns → column labels (optional)

- aggfunc → aggregation function (mean, sum, count, etc.)

In [114]:
## TASK-40

# Summary Tables 
import pandas as pd

# DataFrame: Player runs by team and role
df = pd.DataFrame({
    "Role": ["Batsman", "Batsman", "Bowler", "Bowler"],  # Player roles
    "Team": ["TeamA", "TeamB", "TeamA", "TeamB"],        # Teams
    "Runs": [75, 88, 60, 45]                              # Runs scored
})

# Create pivot table: average runs by Role and Team
summary = df.pivot_table(values="Runs", index="Role", columns="Team", aggfunc="mean")

print("Pivot Table (Average Runs by Role and Team):\n", summary)

Pivot Table (Average Runs by Role and Team):
 Team     TeamA  TeamB
Role
Batsman   75.0   88.0
Bowler    60.0   45.0

In [118]:
## TASK-41

# Summary Table / Pivot Table 
import pandas as pd

# DataFrame: Player runs by Role and Team
df = pd.DataFrame({
    "Role": ["Batsman", "Batsman", "Bowler", "Bowler", "Batsman", "Bowler"],  # Player roles
    "Team": ["TeamA", "TeamB", "TeamA", "TeamB", "TeamA", "TeamB"],            # Teams
    "Runs": [75, 88, 60, 45, 90, 70]                                           # Runs scored
})

# Pivot table: average runs by Role and Team
summary_table = df.pivot_table(values="Runs", index="Role", columns="Team", aggfunc="mean")

print("Summary Table (Average Runs by Role and Team):\n", summary_table)

Summary Table (Average Runs by Role and Team):
 Team     TeamA  TeamB
Role
Batsman   82.5   88.0
Bowler    60.0   57.5

In [120]:
## TASK-42

# Enhanced Pivot Table with Multiple Aggregations 
import pandas as pd

# DataFrame: Player runs by Role and Team
df = pd.DataFrame({
    "Role": ["Batsman", "Batsman", "Bowler", "Bowler", "Batsman", "Bowler"],
    "Team": ["TeamA", "TeamB", "TeamA", "TeamB", "TeamA", "TeamB"],
    "Runs": [75, 88, 60, 45, 90, 70]
})

# Pivot table: calculate mean, sum, and max runs by Role and Team
summary_table = df.pivot_table(
    values="Runs",
    index="Role",
    columns="Team",
    aggfunc=["mean", "sum", "max"]
)

print("Enhanced Pivot Table (Runs stats by Role and Team):\n", summary_table)

Enhanced Pivot Table (Runs stats by Role and Team):
          mean         sum         max
Team    TeamA TeamB TeamA TeamB TeamA TeamB
Role
Batsman  82.5  88.0   165    88    90    88
Bowler   60.0  57.5    60   115    60    70

In [122]:
## TASK-43

# Handling Missing Data in Pivot Tables 
import pandas as pd

# DataFrame: Player runs by Role and Team (some combinations missing)
df = pd.DataFrame({
    "Role": ["Batsman", "Batsman", "Bowler", "Bowler", "Batsman"],
    "Team": ["TeamA", "TeamB", "TeamA", "TeamB", "TeamA"],
    "Runs": [75, 88, 60, 45, 90]
})

# Pivot table: average runs by Role and Team, fill missing with 0
summary_table_fill = df.pivot_table(
    values="Runs",
    index="Role",
    columns="Team",
    aggfunc="mean",
    fill_value=0
)

print("Pivot Table with Missing Values Filled (Runs):\n", summary_table_fill)

Pivot Table with Missing Values Filled (Runs):
 Team     TeamA  TeamB
Role
Batsman   82.5   88.0
Bowler    60.0   45.0

In [124]:
## TASK-44

# Grouping vs Pivot Tables 
import pandas as pd

# DataFrame: Player runs by Role and Team
df = pd.DataFrame({
    "Role": ["Batsman", "Batsman", "Bowler", "Bowler", "Batsman", "Bowler"],
    "Team": ["TeamA", "TeamB", "TeamA", "TeamB", "TeamA", "TeamB"],
    "Runs": [75, 88, 60, 45, 90, 70]
})

# Equivalent of pivot table using groupby + unstack
grouped_equiv = df.groupby(["Role", "Team"])["Runs"].mean().unstack()

print("Equivalent Pivot Table using groupby + unstack:\n", grouped_equiv)

Equivalent Pivot Table using groupby + unstack:
 Team     TeamA  TeamB
Role
Batsman   82.5   88.0
Bowler    60.0   57.5